apiVersion: v1
kind: Service
metadata:
  name: {{ include "meilisearch.fullname" . }}
  labels:
    {{- include "meilisearch.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{.Values.service.externalTrafficPolicy}}
  {{- end }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{.Values.service.loadBalancerIP}}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq "NodePort" .Values.service.type }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      {{- end }}
  selector:
    {{- include "meilisearch.selectorLabels" . | nindent 4 }}
