apiVersion: v1
appVersion: "v1.32.2"
description: A Helm chart for the Meilisearch search engine
name: meilisearch
version: 0.21.0
icon: https://raw.githubusercontent.com/meilisearch/integration-guides/main/assets/logos/logo.svg
home: https://github.com/meilisearch/meilisearch-kubernetes/tree/main/charts/meilisearch
maintainers:
    - name: Bruno
      email: bruno@meilisearch.com
    - name: Clementine
      email: clementine@meilisearch.com
