apiVersion: v1
appVersion: "v0.23.0"
description: A Helm chart for the Meilisearch search engine
name: meilisearch
version: 0.1.17
icon: https://res.cloudinary.com/meilisearch/image/upload/v1597822872/Logo/logo_img.svg
home: https://github.com/meilisearch/meilisearch-kubernetes/charts
maintainers:
    - name: Rene
      email: renehr9102@protonmail.com
    - name: Samuel
      email: samuel@meilisearch.com
    - name: Thomas
      email: thomas@meilisearch.com
