# Default values for <CHARTNAME>.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

startupProbe:
  periodSeconds: 1
  InitialDelaySeconds: 1
  failureThreshold: 60

readinessProbe:
  periodSeconds: 10
  InitialDelaySeconds: 0

livenessProbe:
  periodSeconds: 10
  InitialDelaySeconds: 0

image:
  # -- Meilisearch image name
  repository: getmeili/meilisearch
  # -- Meilisearch image tag
  tag: v1.8.0
  # -- Meilisearch image pull policy
  pullPolicy: IfNotPresent
  # -- Secret to authenticate against the docker registry
  pullSecret:

# -- String to partially override meilisearch.fullname
nameOverride: ""
# -- String to fully override meilisearch.fullname
fullnameOverride: ""

# Environment loaded into the configMap
environment:
  # -- Deactivates analytics
  MEILI_NO_ANALYTICS: true
  # -- Sets the environment. Either **production** or **development**
  MEILI_ENV: development
  # For production deployment, the environment MEILI_MASTER_KEY is required.
  # If MEILI_ENV is set to "production" without setting MEILI_MASTER_KEY, this
  # chart will automatically create a secure MEILI_MASTER_KEY and push it as a
  # secret. Otherwise the below value of MEILI_MASTER_KEY will be used instead.
  # MEILI_MASTER_KEY: ""
auth:
  # -- Use an existing Kubernetes secret for the MEILI_MASTER_KEY
  existingMasterKeySecret: ""

# -- Additional environment variables from ConfigMap or secrets
envFrom: []

serviceAccount:
  # You can use a specific pre-created service account instead of
  # the one created by this chart.
  # Set create to false to prevent creating a service account and use your own.
  # -- Should this chart create a service account
  create: true
  # -- Custom service account name, if not created by this chart
  name: ""
  # -- Additional annotations for created service account
  annotations: {}

podAnnotations: {}

# -- Additional labels to add to the pod(s) only
podLabels: {}

# -- Additional labels to add to all resources
customLabels: {}

# -- Service HTTP port
service:
  # -- Kubernetes Service type
  type: ClusterIP
  port: 7700
  # -- Additional annotations for service
  annotations: {}

container:
  containerPort: 7700

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch

securityContext:
  capabilities:
    drop:
      - ALL
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

ingress:
  # -- Enable ingress controller resource
  enabled: false
  # -- Ingress ingressClassName
  className: nginx
  # -- Ingress annotations
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
  # -- Path within the host
  path: /
  # -- List of hostnames
  hosts:
    - meilisearch-example.local
  # -- TLS specification
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistence:
  # -- Enable persistence using PVC
  enabled: false
  # -- PVC Access Mode
  accessMode: ReadWriteOnce
  ## Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # -- PVC Storage Class
  storageClass: "-"

  ## Data Persistent Volume existing claim name
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # -- Existing PVC
  existingClaim: ""
  # -- PVC Storage Request
  size: 10Gi
  # -- Additional annotations for PVC
  annotations: {}
  volume:
    name: data
    mountPath: /meili_data

# -- Resources allocation (Requests and Limits)
resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

# -- Additional volumes for pod
volumes: []

# -- Additional volumes to mount on pod
volumeMounts: []

# -- Additional containers for pod
containers: []

# -- Additional initContainers for pod
initContainers: []

# -- Node labels for pod assignment
nodeSelector: {}

# -- Tolerations for pod assignment
tolerations: []

# -- Affinity for pod assignment
affinity: {}

# -- Pod command
command: []

# -- Monitoring with Prometheus Operator
serviceMonitor:
  # -- Enable ServiceMonitor to configure scraping
  enabled: false
  # -- Set of labels to transfer from the Kubernetes Service onto the target
  additionalLabels: {}
  # -- Set scraping frequency
  interval: 1m
  # -- Set scraping timeout
  scrapeTimeout: 10s
  # -- Set path to metrics
  telemetryPath: /metrics
  # -- Set of labels to transfer from the Kubernetes Service onto the target
  targetLabels: []
  # -- MetricRelabelConfigs to apply to samples before ingestion
  metricRelabelings: []
  # -- Set relabel_configs as per https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
  relabelings: []
